### ISSUE TITLE
Suggest: move module "multer" into dependencies from peerDependencise(or devDependencies) ?

### ISSUE THREAD

**Issue by Froguard** [koajs/multer#2] opened 2019-08-02 13:23 UTC
Discuss: Move module "multer" into dependencies from devDependencise and peerDependencies. 

```
npm WARN @koa/multer@2.0.0 requires a peer of multer@* but none is installed. You must install peer dependencies yourself.
```
**The warning via the `console.warn` is easily overlooked.**

index.js

```js
/**
 * Module dependencies.
 */

const originalMulter = require('multer');
```

package.json

```js
//...
"peerDependencies": {
  "multer": "*"
},
"dependencies": {},
"devDependencies": {
  //...
  "multer": "^1.3.0",
  //...
```

**Comment by niftylettuce** [comment] 2019-08-02 16:11
This is not a bug.  Stop opening and re-closing the issue please.

**Comment by niftylettuce** [comment] 2019-08-02 16:11
Please see the README.  You MUST install multer@1.x (buffer) or multer@2.x (streams) yourself.

**Closed by niftylettuce** 2019-08-02 16:11 UTC
